"use strict";
const $ = id => document.getElementById(id);
const el = (tag, cls, text) => { const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; };
let state=null, selected=null, busy=false;
async function get(path){const r=await fetch(path,{cache:"no-store",credentials:"same-origin",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);return r.json();}
function badge(text){return el("span","badge "+String(text).toLowerCase(),text);}
function stat(label,value){const n=el("div","workspace-stat");n.append(el("strong","",String(value)),el("span","",label));return n;}
function section(title){const n=el("section","detail-section");n.append(el("h4","detail-label",title));return n;}
function list(items,format=x=>String(x)){const n=el("ul","gap-list");for(const item of items)n.append(el("li","",format(item)));return n;}
function renderModels(){const box=$("team");box.replaceChildren();for(const [role,model] of Object.entries(state.models)){const card=el("article","team-card");card.append(el("span","role-icon "+role,role==="worker"?"K":role==="manager"?"◇":"✓"));const copy=el("div","role-copy"),title=el("div","role-title",model.name);title.append(el("span","role-tag",role));copy.append(title,el("div","role-model",model.route),el("div","role-provider",model.effort+" effort"));card.append(copy);box.append(card);}}
function renderList(){const q=$("search").value.toLowerCase(),f=$("filter").value;const rows=state.engagements.filter(x=>(f==="all"||x.status===f)&&`${x.id} ${x.target}`.toLowerCase().includes(q));$("engagement-count").textContent=rows.length;const box=$("engagement-list");box.replaceChildren();if(!rows.length){const e=el("div","empty-list");e.append(el("span","empty-symbol","◇"),el("h3","","No matching engagements"),el("code","","grypton init --target HOST"));box.append(e);return;}for(const row of rows){const b=el("button","case-item"+(selected===row.id?" selected":""));b.type="button";const top=el("div","case-topline");top.append(el("span","case-id","ENG / "+row.id.toUpperCase()),badge(row.status));b.append(top,el("div","case-title",row.target));const meta=el("div","case-meta");meta.append(el("span","",`${row.turns} turns`),el("span","",`${row.tool_calls} tools`),el("span","",`${row.flows} flows`),el("span","",`${row.confirmed}/${row.findings} confirmed`));b.append(meta);b.onclick=()=>{selected=row.id;renderList();loadDetail();};box.append(b);}}
function keyValue(title,rows){const s=section(title),grid=el("div","kv-grid");for(const [k,v] of rows){const r=el("div","kv-row");r.append(el("span","kv-key",k),el("span","kv-value",String(v)));grid.append(r);}s.append(grid);return s;}
function renderDetail(d){const box=$("detail");box.replaceChildren();const h=el("div","detail-heading");h.append(el("span","detail-eyebrow","ENGAGEMENT / "+d.id.toUpperCase()),badge(d.status));box.append(h,el("h3","detail-title",d.target));const stats=el("div","workspace-stats");stats.append(stat("turns",d.turns),stat("tool calls",d.tool_calls),stat("flows",d.flows),stat("confirmed",`${d.confirmed}/${d.findings}`));box.append(stats);
box.append(keyValue("PINNED ROUTE ACTIVITY",[["Kraude calls",d.provider_calls.worker],["Kryptex calls",d.provider_calls.manager],["Astra calls",d.provider_calls.validator],["workspace",d.workspace]]));
const scope=section("BINDING SCOPE");scope.append(list([`in: ${d.scope.in_scope.join(", ")||"—"}`,`out: ${d.scope.out_of_scope.join(", ")||"—"}`,...d.scope.hard_rules]));box.append(scope);
if(d.tool_rows.length){const s=section("RECENT TOOL ACTIVITY");s.append(list(d.tool_rows.slice(-20).reverse(),x=>`${x.ok?"✓":"!"} ${x.tool} · ${x.summary}`));box.append(s);}
if(d.flow_rows.length){const s=section("BURP-LIKE CAPTURES");s.append(list(d.flow_rows.slice(0,20),x=>`${x.id} · ${x.bytes} bytes`));box.append(s);}
if(d.finding_rows.length){const s=section("FINDINGS / ASTRA VERDICTS");for(const f of d.finding_rows.slice().reverse()){const c=el("article","finding-card"),top=el("div","finding-top"),state=f.manager_verdict?.verdict||(f.status==="validation-not-requested"?"not-requested":"pending");top.append(el("span","finding-id",f.id),badge(state));const sev=f.manager_verdict?.severity||f.severity,detail=f.manager_verdict?.reasoning||f.description||(state==="not-requested"?"Astra review was not requested; automatic validation is limited to P1/P2.":"Awaiting independent validation.");c.append(top,el("h5","",`${sev} · ${f.title}`),el("p","detail-text",detail));s.append(c);}box.append(s);}
if(d.surface_rows.length){const s=section("RECENT ATTACK SURFACE");s.append(list(d.surface_rows.slice(-20).reverse(),x=>`${x.kind||"item"} · ${x.item}`));box.append(s);}
if(d.tested_rows.length){const s=section("RECENT TESTED TECHNIQUES");s.append(list(d.tested_rows.slice(-20).reverse(),x=>`${x.surface} · ${x.technique} → ${x.result}`));box.append(s);}
if(d.last_directive)box.append(keyValue("NEXT KRYPTEX DIRECTIVE",[["directive",d.last_directive]]));}
async function loadDetail(){if(!selected)return;try{renderDetail(await get("/api/engagements/"+encodeURIComponent(selected)));}catch(e){$("detail").replaceChildren(el("p","detail-text",e.message));}}
async function refresh(){if(busy)return;busy=true;$("refresh").disabled=true;try{state=await get("/api/state");for(const k of ["engagements","running","tools"])$("count-"+k).textContent=state.counts[k];$("count-findings").textContent=`${state.counts.confirmed}/${state.counts.findings}`;$("nav-count").textContent=state.counts.engagements;renderModels();if(!selected&&state.engagements.length)selected=state.engagements[0].id;if(selected&&!state.engagements.some(x=>x.id===selected))selected=null;renderList();if(selected)await loadDetail();$("connection-label").textContent="Connected";$("connection-dot").classList.remove("offline");$("error-banner").hidden=true;$("updated").textContent="Updated "+new Date().toLocaleTimeString();}catch(e){$("error-banner").textContent=e.message;$("error-banner").hidden=false;$("connection-label").textContent="Disconnected";$("connection-dot").classList.add("offline");}finally{busy=false;$("refresh").disabled=false;}}
$("search").oninput=renderList;$("filter").onchange=renderList;$("refresh").onclick=refresh;
function tick(){$("clock").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}tick();refresh();setInterval(tick,30000);setInterval(()=>{if(!document.hidden)refresh();},5000);
